/*
 * generated by Xtext 2.10.0
 */
package ac.soton.xeventb.xcontext.ui.tests;

import com.google.inject.Injector;

import ac.soton.xeventb.xcontext.ui.internal.ContextActivator;

import org.eclipse.xtext.junit4.IInjectorProvider;

public class XContextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ContextActivator.getInstance().getInjector("ac.soton.eventb.xtext.context.XContext");
	}

}
