/**
 * generated by Xtext 2.11.0
 */
package ac.soton.xeventb.xcontext.tests;

import ac.soton.xeventb.tests.common.AssertContextExtensions;
import ac.soton.xeventb.tests.common.AssertExtensions;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eventb.emf.core.context.Context;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * @since 1.0
 */
@RunWith(XtextRunner.class)
@InjectWith(XContextInjectorProvider.class)
@SuppressWarnings("all")
public class XContextParsingTest {
  @Inject
  @Extension
  private ParseHelper<Context> parseHelper;

  @Extension
  private AssertExtensions _assertExtensions = new AssertExtensions();

  @Extension
  private AssertContextExtensions _assertContextExtensions = new AssertContextExtensions();

  /**
   * Manually register any EPackage required for running the tests.
   * @since 1.0
   */
  @Before
  public void registerEPackages() {
    this._assertContextExtensions.registerContextEPackage();
  }

  /**
   * Successful test for context clause.
   * 
   * @since 1.0
   */
  @Test
  public void testContextClauseSuccessful() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      this._assertContextExtensions.assertContext(result, "c0", null);
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for multi-line comments with context clause.
   * 
   * @since 1.0
   */
  @Test
  public void testContextClauseSuccessful_ML_COMMENT() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("/* ");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("* Multi-line");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("* comments");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("*/");
      _builder.newLine();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      this._assertContextExtensions.assertContext(result, "c0", null);
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for single-line comments with context clause.
   * 
   * @since 1.0
   */
  @Test
  public void testContextClauseSuccessful_SL_COMMENT() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("// Single-line comment");
      _builder.newLine();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      this._assertContextExtensions.assertContext(result, "c0", null);
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Test for erroneous context clause.
   * 
   * @since 1.0
   */
  @Test
  public void testContextClauseFailed_ErrornousName() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context 0c");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertNotEmpty(errors);
      this._assertExtensions.assertLength(errors, 1);
      this._assertExtensions.assertErrorDetails(errors.get(0), 
        "extraneous input \'0\' expecting RULE_ID", null, 9, 1);
      Assert.assertTrue((result instanceof Context));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for sets clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupSets_OneSet_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("sets S");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result, "S:");
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for sets clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupSets_OneSet_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("sets S");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result, "S:");
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for sets clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupSets_TwoSets_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("sets S T");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result, "S:", "T:");
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for sets clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupSets_TwoSets_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("sets S T");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result, "S:", "T:");
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for constants clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupConstants_OneConstant_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("constants a");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result, "a:");
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for constants clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupConstants_OneConstant_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("constants a");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result, "a:");
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for constants clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupConstants_TwoConstants_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("constants a b");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result, "a:", "b:");
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for constants clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupConstants_TwoConstants_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("constants a b");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result, "a:", "b:");
      this._assertContextExtensions.assertContextAxioms(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_SingleAxiom_OneAxiom_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axiom @axm1: a ∈ S");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_SingleAxiom_OneAxiom_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axiom @axm1: a ∈ S");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_SingeAxiom_TwoAxioms_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axiom @axm1: a ∈ S");
      _builder.newLine();
      _builder.append("axiom @axm2: b ∈ T");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:", "axm2:b ∈ T:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_SingeAxiom_TwoAxioms_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axiom @axm1: a ∈ S");
      _builder.newLine();
      _builder.append("axiom @axm2: b ∈ T");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:", "axm2:b ∈ T:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupAxiom_OneAxiom_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axioms ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm1: a ∈ S");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupAxioms_OneAxiom_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axioms ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm1: a ∈ S");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupAxioms_TwoAxioms_WithEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axioms ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm1: a ∈ S");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm2: b ∈ T");
      _builder.newLine();
      _builder.append("end");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:", "axm2:b ∈ T:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  /**
   * Successful test for for axioms clause.
   * 
   * @since 3.0
   */
  @Test
  public void testSetsClauseSuccessful_GroupAxioms_TwoAxioms_NoEnd() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("context c0");
      _builder.newLine();
      _builder.append("axioms ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm1: a ∈ S");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("@axm2: b ∈ T");
      _builder.newLine();
      final String testInput = _builder.toString();
      final Context result = this.parseHelper.parse(testInput);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      this._assertExtensions.assertEmpty(errors);
      Assert.assertTrue((result instanceof Context));
      Assert.assertEquals("c0", result.getName());
      this._assertContextExtensions.assertContextExtendsNames(result);
      this._assertContextExtensions.assertContextSets(result);
      this._assertContextExtensions.assertContextConstants(result);
      this._assertContextExtensions.assertContextAxioms(result, "axm1:a ∈ S:false:", "axm2:b ∈ T:false:");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
