/*
 * generated by Xtext
 */
package ac.soton.xeventb.xmachine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XMachineUiModule extends ac.soton.xeventb.xmachine.ui.AbstractXMachineUiModule {
	public XMachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
