/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xeventb.xmachine.ui;

import ac.soton.xeventb.xmachine.ui.internal.XmachineActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XmachineActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XmachineActivator activator = XmachineActivator.getInstance();
		return activator != null ? activator.getInjector(XmachineActivator.AC_SOTON_XEVENTB_XMACHINE_XMACHINE) : null;
	}

}
