/**
 * generated by Xtext 2.11.0
 */
package ac.soton.xeventb.xstatemachine;

import ac.soton.xeventb.xstatemachine.XStatemachineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XStatemachineStandaloneSetup extends XStatemachineStandaloneSetupGenerated {
  public static void doSetup() {
    new XStatemachineStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
