/**
 * generated by Xtext 2.11.0
 */
package ac.soton.xeventb.xstatemachine.ide;

import ac.soton.xeventb.xstatemachine.ide.AbstractXStatemachineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XStatemachineIdeModule extends AbstractXStatemachineIdeModule {
}
