/*
 * generated by Xtext 2.11.0
 */
package ac.soton.xeventb.xstatemachine.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XStatemachineUiModule extends AbstractXStatemachineUiModule {
}
