/*
 * generated by Xtext 2.13.0
 */
package ac.soton.xeventb.xmachine.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class XMachineGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.Machine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMachineAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cCommentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cCommentAlternatives_1_0 = (Alternatives)cCommentAssignment_1.eContents().get(0);
		private final RuleCall cCommentML_COMMENTTerminalRuleCall_1_0_0 = (RuleCall)cCommentAlternatives_1_0.eContents().get(0);
		private final RuleCall cCommentSL_COMMENTTerminalRuleCall_1_0_1 = (RuleCall)cCommentAlternatives_1_0.eContents().get(1);
		private final Keyword cMachineKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Assignment cExtensionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExtensionsMIncludesParserRuleCall_4_0 = (RuleCall)cExtensionsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRefinesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRefinesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cRefinesMachineCrossReference_5_1_0 = (CrossReference)cRefinesAssignment_5_1.eContents().get(0);
		private final RuleCall cRefinesMachineIDTerminalRuleCall_5_1_0_1 = (RuleCall)cRefinesMachineCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSeesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSeesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSeesContextCrossReference_6_1_0 = (CrossReference)cSeesAssignment_6_1.eContents().get(0);
		private final RuleCall cSeesContextIDTerminalRuleCall_6_1_0_1 = (RuleCall)cSeesContextCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cVariablesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cVariablesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cVariablesXVariableParserRuleCall_7_1_0 = (RuleCall)cVariablesAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cInvariantsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cInvariantsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cInvariantsXInvariantParserRuleCall_8_1_0 = (RuleCall)cInvariantsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cVariantKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cVariantAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cVariantXVariantParserRuleCall_9_1_0 = (RuleCall)cVariantAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cEventsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cEventsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cEventsXEventParserRuleCall_10_1_0 = (RuleCall)cEventsAssignment_10_1.eContents().get(0);
		private final Assignment cEventsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cEventsXEventParserRuleCall_10_2_0 = (RuleCall)cEventsAssignment_10_2.eContents().get(0);
		private final Keyword cEndKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		///*
		// * For XEvent-B 0.0.8 comments are allowed everywhere
		// * ML_COMMENT and SL_COMMEN are defined as hidden
		// */ Machine emachine::Machine:
		//	{emachine::Machine} comment=(ML_COMMENT | SL_COMMENT)?
		//	'machine' name=ID
		//	extensions+=MIncludes* ('refines' refines+=[emachine::Machine])? ('sees' sees+=[econtext::Context]+)? ('variables'
		//	variables+=XVariable+)? ('invariants' invariants+=XInvariant+)? ('variant' variant=XVariant)? ('events' events+=XEvent
		//	events+=XEvent*)?
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Machine} comment=(ML_COMMENT | SL_COMMENT)? 'machine' name=ID extensions+=MIncludes* ('refines'
		//refines+=[emachine::Machine])? ('sees' sees+=[econtext::Context]+)? ('variables' variables+=XVariable+)? ('invariants'
		//invariants+=XInvariant+)? ('variant' variant=XVariant)? ('events' events+=XEvent events+=XEvent*)? 'end'
		public Group getGroup() { return cGroup; }
		
		//{emachine::Machine}
		public Action getMachineAction_0() { return cMachineAction_0; }
		
		//comment=(ML_COMMENT | SL_COMMENT)?
		public Assignment getCommentAssignment_1() { return cCommentAssignment_1; }
		
		//(ML_COMMENT | SL_COMMENT)
		public Alternatives getCommentAlternatives_1_0() { return cCommentAlternatives_1_0; }
		
		//ML_COMMENT
		public RuleCall getCommentML_COMMENTTerminalRuleCall_1_0_0() { return cCommentML_COMMENTTerminalRuleCall_1_0_0; }
		
		//SL_COMMENT
		public RuleCall getCommentSL_COMMENTTerminalRuleCall_1_0_1() { return cCommentSL_COMMENTTerminalRuleCall_1_0_1; }
		
		//'machine'
		public Keyword getMachineKeyword_2() { return cMachineKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//extensions+=MIncludes*
		public Assignment getExtensionsAssignment_4() { return cExtensionsAssignment_4; }
		
		//MIncludes
		public RuleCall getExtensionsMIncludesParserRuleCall_4_0() { return cExtensionsMIncludesParserRuleCall_4_0; }
		
		//('refines' refines+=[emachine::Machine])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'refines'
		public Keyword getRefinesKeyword_5_0() { return cRefinesKeyword_5_0; }
		
		//refines+=[emachine::Machine]
		public Assignment getRefinesAssignment_5_1() { return cRefinesAssignment_5_1; }
		
		//[emachine::Machine]
		public CrossReference getRefinesMachineCrossReference_5_1_0() { return cRefinesMachineCrossReference_5_1_0; }
		
		//ID
		public RuleCall getRefinesMachineIDTerminalRuleCall_5_1_0_1() { return cRefinesMachineIDTerminalRuleCall_5_1_0_1; }
		
		//('sees' sees+=[econtext::Context]+)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'sees'
		public Keyword getSeesKeyword_6_0() { return cSeesKeyword_6_0; }
		
		//sees+=[econtext::Context]+
		public Assignment getSeesAssignment_6_1() { return cSeesAssignment_6_1; }
		
		//[econtext::Context]
		public CrossReference getSeesContextCrossReference_6_1_0() { return cSeesContextCrossReference_6_1_0; }
		
		//ID
		public RuleCall getSeesContextIDTerminalRuleCall_6_1_0_1() { return cSeesContextIDTerminalRuleCall_6_1_0_1; }
		
		//('variables' variables+=XVariable+)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'variables'
		public Keyword getVariablesKeyword_7_0() { return cVariablesKeyword_7_0; }
		
		//variables+=XVariable+
		public Assignment getVariablesAssignment_7_1() { return cVariablesAssignment_7_1; }
		
		//XVariable
		public RuleCall getVariablesXVariableParserRuleCall_7_1_0() { return cVariablesXVariableParserRuleCall_7_1_0; }
		
		//('invariants' invariants+=XInvariant+)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'invariants'
		public Keyword getInvariantsKeyword_8_0() { return cInvariantsKeyword_8_0; }
		
		//invariants+=XInvariant+
		public Assignment getInvariantsAssignment_8_1() { return cInvariantsAssignment_8_1; }
		
		//XInvariant
		public RuleCall getInvariantsXInvariantParserRuleCall_8_1_0() { return cInvariantsXInvariantParserRuleCall_8_1_0; }
		
		//('variant' variant=XVariant)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'variant'
		public Keyword getVariantKeyword_9_0() { return cVariantKeyword_9_0; }
		
		//variant=XVariant
		public Assignment getVariantAssignment_9_1() { return cVariantAssignment_9_1; }
		
		//XVariant
		public RuleCall getVariantXVariantParserRuleCall_9_1_0() { return cVariantXVariantParserRuleCall_9_1_0; }
		
		//('events' events+=XEvent events+=XEvent*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'events'
		public Keyword getEventsKeyword_10_0() { return cEventsKeyword_10_0; }
		
		//events+=XEvent
		public Assignment getEventsAssignment_10_1() { return cEventsAssignment_10_1; }
		
		//XEvent
		public RuleCall getEventsXEventParserRuleCall_10_1_0() { return cEventsXEventParserRuleCall_10_1_0; }
		
		//events+=XEvent*
		public Assignment getEventsAssignment_10_2() { return cEventsAssignment_10_2; }
		
		//XEvent
		public RuleCall getEventsXEventParserRuleCall_10_2_0() { return cEventsXEventParserRuleCall_10_2_0; }
		
		//'end'
		public Keyword getEndKeyword_11() { return cEndKeyword_11; }
	}
	public class MIncludesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.MIncludes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMachineInclusionAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cIncludesKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAbstractMachineAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cAbstractMachineMachineCrossReference_1_1_0 = (CrossReference)cAbstractMachineAssignment_1_1.eContents().get(0);
		private final RuleCall cAbstractMachineMachineQualifiedNameParserRuleCall_1_1_0_1 = (RuleCall)cAbstractMachineMachineCrossReference_1_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cToKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cConcreteMachineAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cConcreteMachineMachineCrossReference_2_1_0 = (CrossReference)cConcreteMachineAssignment_2_1.eContents().get(0);
		private final RuleCall cConcreteMachineMachineIDTerminalRuleCall_2_1_0_1 = (RuleCall)cConcreteMachineMachineCrossReference_2_1_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPrefixesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPrefixesIDTerminalRuleCall_3_1_0 = (RuleCall)cPrefixesAssignment_3_1.eContents().get(0);
		private final Assignment cPrefixesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPrefixesIDTerminalRuleCall_3_2_0 = (RuleCall)cPrefixesAssignment_3_2.eContents().get(0);
		
		//MIncludes einclusion::MachineInclusion:
		//	{einclusion::MachineInclusion} ('includes' abstractMachine=[emachine::Machine|QualifiedName]) ('to'
		//	concreteMachine=[emachine::Machine])? ('as' prefixes+=ID prefixes+=ID*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{einclusion::MachineInclusion} ('includes' abstractMachine=[emachine::Machine|QualifiedName]) ('to'
		//concreteMachine=[emachine::Machine])? ('as' prefixes+=ID prefixes+=ID*)?
		public Group getGroup() { return cGroup; }
		
		//{einclusion::MachineInclusion}
		public Action getMachineInclusionAction_0() { return cMachineInclusionAction_0; }
		
		//'includes' abstractMachine=[emachine::Machine|QualifiedName]
		public Group getGroup_1() { return cGroup_1; }
		
		//'includes'
		public Keyword getIncludesKeyword_1_0() { return cIncludesKeyword_1_0; }
		
		//abstractMachine=[emachine::Machine|QualifiedName]
		public Assignment getAbstractMachineAssignment_1_1() { return cAbstractMachineAssignment_1_1; }
		
		//[emachine::Machine|QualifiedName]
		public CrossReference getAbstractMachineMachineCrossReference_1_1_0() { return cAbstractMachineMachineCrossReference_1_1_0; }
		
		//QualifiedName
		public RuleCall getAbstractMachineMachineQualifiedNameParserRuleCall_1_1_0_1() { return cAbstractMachineMachineQualifiedNameParserRuleCall_1_1_0_1; }
		
		//('to' concreteMachine=[emachine::Machine])?
		public Group getGroup_2() { return cGroup_2; }
		
		//'to'
		public Keyword getToKeyword_2_0() { return cToKeyword_2_0; }
		
		//concreteMachine=[emachine::Machine]
		public Assignment getConcreteMachineAssignment_2_1() { return cConcreteMachineAssignment_2_1; }
		
		//[emachine::Machine]
		public CrossReference getConcreteMachineMachineCrossReference_2_1_0() { return cConcreteMachineMachineCrossReference_2_1_0; }
		
		//ID
		public RuleCall getConcreteMachineMachineIDTerminalRuleCall_2_1_0_1() { return cConcreteMachineMachineIDTerminalRuleCall_2_1_0_1; }
		
		//('as' prefixes+=ID prefixes+=ID*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'as'
		public Keyword getAsKeyword_3_0() { return cAsKeyword_3_0; }
		
		//prefixes+=ID
		public Assignment getPrefixesAssignment_3_1() { return cPrefixesAssignment_3_1; }
		
		//ID
		public RuleCall getPrefixesIDTerminalRuleCall_3_1_0() { return cPrefixesIDTerminalRuleCall_3_1_0; }
		
		//prefixes+=ID*
		public Assignment getPrefixesAssignment_3_2() { return cPrefixesAssignment_3_2; }
		
		//ID
		public RuleCall getPrefixesIDTerminalRuleCall_3_2_0() { return cPrefixesIDTerminalRuleCall_3_2_0; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)?;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)?
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class XVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XVariable emachine::Variable:
		//	{emachine::Variable} name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Variable} name=ID
		public Group getGroup() { return cGroup; }
		
		//{emachine::Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class XInvariantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XInvariant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInvariantAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameXLABELTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPredicateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPredicateXPredicateParserRuleCall_2_0 = (RuleCall)cPredicateAssignment_2.eContents().get(0);
		private final Assignment cTheoremAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cTheoremTheoremKeyword_3_0 = (Keyword)cTheoremAssignment_3.eContents().get(0);
		
		//XInvariant emachine::Invariant:
		//	{emachine::Invariant} name=XLABEL predicate=XPredicate theorem?='theorem'?;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Invariant} name=XLABEL predicate=XPredicate theorem?='theorem'?
		public Group getGroup() { return cGroup; }
		
		//{emachine::Invariant}
		public Action getInvariantAction_0() { return cInvariantAction_0; }
		
		//name=XLABEL
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//XLABEL
		public RuleCall getNameXLABELTerminalRuleCall_1_0() { return cNameXLABELTerminalRuleCall_1_0; }
		
		//predicate=XPredicate
		public Assignment getPredicateAssignment_2() { return cPredicateAssignment_2; }
		
		//XPredicate
		public RuleCall getPredicateXPredicateParserRuleCall_2_0() { return cPredicateXPredicateParserRuleCall_2_0; }
		
		//theorem?='theorem'?
		public Assignment getTheoremAssignment_3() { return cTheoremAssignment_3; }
		
		//'theorem'
		public Keyword getTheoremTheoremKeyword_3_0() { return cTheoremTheoremKeyword_3_0; }
	}
	public class XVariantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XVariant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariantAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cExpressionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpressionXPredicateParserRuleCall_1_0 = (RuleCall)cExpressionAssignment_1.eContents().get(0);
		
		//XVariant emachine::Variant:
		//	{emachine::Variant} expression=XPredicate;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Variant} expression=XPredicate
		public Group getGroup() { return cGroup; }
		
		//{emachine::Variant}
		public Action getVariantAction_0() { return cVariantAction_0; }
		
		//expression=XPredicate
		public Assignment getExpressionAssignment_1() { return cExpressionAssignment_1; }
		
		//XPredicate
		public RuleCall getExpressionXPredicateParserRuleCall_1_0() { return cExpressionXPredicateParserRuleCall_1_0; }
	}
	public class XEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cExtendedAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cExtendedExtendedKeyword_2_0_0 = (Keyword)cExtendedAssignment_2_0.eContents().get(0);
		private final Assignment cConvergenceAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final RuleCall cConvergenceXConvergenceEnumRuleCall_2_1_0 = (RuleCall)cConvergenceAssignment_2_1.eContents().get(0);
		private final Assignment cExtensionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExtensionsEventSyncParserRuleCall_3_0 = (RuleCall)cExtensionsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRefinesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRefinesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cRefinesEventCrossReference_4_1_0 = (CrossReference)cRefinesAssignment_4_1.eContents().get(0);
		private final RuleCall cRefinesEventIDTerminalRuleCall_4_1_0_1 = (RuleCall)cRefinesEventCrossReference_4_1_0.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Group cGroup_5_0 = (Group)cAlternatives_5.eContents().get(0);
		private final Group cGroup_5_0_0 = (Group)cGroup_5_0.eContents().get(0);
		private final Keyword cWithKeyword_5_0_0_0 = (Keyword)cGroup_5_0_0.eContents().get(0);
		private final Assignment cWitnessesAssignment_5_0_0_1 = (Assignment)cGroup_5_0_0.eContents().get(1);
		private final RuleCall cWitnessesXWitnessParserRuleCall_5_0_0_1_0 = (RuleCall)cWitnessesAssignment_5_0_0_1.eContents().get(0);
		private final Keyword cBeginKeyword_5_0_1 = (Keyword)cGroup_5_0.eContents().get(1);
		private final Assignment cActionsAssignment_5_0_2 = (Assignment)cGroup_5_0.eContents().get(2);
		private final RuleCall cActionsXActionParserRuleCall_5_0_2_0 = (RuleCall)cActionsAssignment_5_0_2.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cAlternatives_5.eContents().get(1);
		private final Keyword cWhenKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cGuardsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cGuardsXGuardParserRuleCall_5_1_1_0 = (RuleCall)cGuardsAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_5_1_2 = (Group)cGroup_5_1.eContents().get(2);
		private final Keyword cWithKeyword_5_1_2_0 = (Keyword)cGroup_5_1_2.eContents().get(0);
		private final Assignment cWitnessesAssignment_5_1_2_1 = (Assignment)cGroup_5_1_2.eContents().get(1);
		private final RuleCall cWitnessesXWitnessParserRuleCall_5_1_2_1_0 = (RuleCall)cWitnessesAssignment_5_1_2_1.eContents().get(0);
		private final Group cGroup_5_1_3 = (Group)cGroup_5_1.eContents().get(3);
		private final Keyword cThenKeyword_5_1_3_0 = (Keyword)cGroup_5_1_3.eContents().get(0);
		private final Assignment cActionsAssignment_5_1_3_1 = (Assignment)cGroup_5_1_3.eContents().get(1);
		private final RuleCall cActionsXActionParserRuleCall_5_1_3_1_0 = (RuleCall)cActionsAssignment_5_1_3_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cAlternatives_5.eContents().get(2);
		private final Keyword cAnyKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cParametersAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cParametersXParameterParserRuleCall_5_2_1_0 = (RuleCall)cParametersAssignment_5_2_1.eContents().get(0);
		private final Keyword cWhereKeyword_5_2_2 = (Keyword)cGroup_5_2.eContents().get(2);
		private final Assignment cGuardsAssignment_5_2_3 = (Assignment)cGroup_5_2.eContents().get(3);
		private final RuleCall cGuardsXGuardParserRuleCall_5_2_3_0 = (RuleCall)cGuardsAssignment_5_2_3.eContents().get(0);
		private final Group cGroup_5_2_4 = (Group)cGroup_5_2.eContents().get(4);
		private final Keyword cWithKeyword_5_2_4_0 = (Keyword)cGroup_5_2_4.eContents().get(0);
		private final Assignment cWitnessesAssignment_5_2_4_1 = (Assignment)cGroup_5_2_4.eContents().get(1);
		private final RuleCall cWitnessesXWitnessParserRuleCall_5_2_4_1_0 = (RuleCall)cWitnessesAssignment_5_2_4_1.eContents().get(0);
		private final Group cGroup_5_2_5 = (Group)cGroup_5_2.eContents().get(5);
		private final Keyword cThenKeyword_5_2_5_0 = (Keyword)cGroup_5_2_5.eContents().get(0);
		private final Assignment cActionsAssignment_5_2_5_1 = (Assignment)cGroup_5_2_5.eContents().get(1);
		private final RuleCall cActionsXActionParserRuleCall_5_2_5_1_0 = (RuleCall)cActionsAssignment_5_2_5_1.eContents().get(0);
		private final Keyword cEndKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//XEvent emachine::Event:
		//	{emachine::Event} name=ID (extended?='extended'? & convergence=XConvergence?) extensions+=EventSync* ('refines'
		//	refines+=[emachine::Event]+)? (('with' witnesses+=XWitness+)?
		//	'begin'
		//	actions+=XAction+
		//	|
		//	'when'
		//	guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then'
		//	actions+=XAction+)?
		//	|
		//	'any'
		//	parameters+=XParameter+
		//	'where'
		//	guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then'
		//	actions+=XAction+)?)?
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Event} name=ID (extended?='extended'? & convergence=XConvergence?) extensions+=EventSync* ('refines'
		//refines+=[emachine::Event]+)? (('with' witnesses+=XWitness+)? 'begin' actions+=XAction+ | 'when' guards+=XGuard+
		//('with' witnesses+=XWitness+)? ('then' actions+=XAction+)? | 'any' parameters+=XParameter+ 'where' guards+=XGuard+
		//('with' witnesses+=XWitness+)? ('then' actions+=XAction+)?)? 'end'
		public Group getGroup() { return cGroup; }
		
		//{emachine::Event}
		public Action getEventAction_0() { return cEventAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//extended?='extended'? & convergence=XConvergence?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//extended?='extended'?
		public Assignment getExtendedAssignment_2_0() { return cExtendedAssignment_2_0; }
		
		//'extended'
		public Keyword getExtendedExtendedKeyword_2_0_0() { return cExtendedExtendedKeyword_2_0_0; }
		
		//convergence=XConvergence?
		public Assignment getConvergenceAssignment_2_1() { return cConvergenceAssignment_2_1; }
		
		//XConvergence
		public RuleCall getConvergenceXConvergenceEnumRuleCall_2_1_0() { return cConvergenceXConvergenceEnumRuleCall_2_1_0; }
		
		//extensions+=EventSync*
		public Assignment getExtensionsAssignment_3() { return cExtensionsAssignment_3; }
		
		//EventSync
		public RuleCall getExtensionsEventSyncParserRuleCall_3_0() { return cExtensionsEventSyncParserRuleCall_3_0; }
		
		//('refines' refines+=[emachine::Event]+)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'refines'
		public Keyword getRefinesKeyword_4_0() { return cRefinesKeyword_4_0; }
		
		//refines+=[emachine::Event]+
		public Assignment getRefinesAssignment_4_1() { return cRefinesAssignment_4_1; }
		
		//[emachine::Event]
		public CrossReference getRefinesEventCrossReference_4_1_0() { return cRefinesEventCrossReference_4_1_0; }
		
		//ID
		public RuleCall getRefinesEventIDTerminalRuleCall_4_1_0_1() { return cRefinesEventIDTerminalRuleCall_4_1_0_1; }
		
		//(('with' witnesses+=XWitness+)? 'begin' actions+=XAction+ | 'when' guards+=XGuard+ ('with' witnesses+=XWitness+)?
		//('then' actions+=XAction+)? | 'any' parameters+=XParameter+ 'where' guards+=XGuard+ ('with' witnesses+=XWitness+)?
		//('then' actions+=XAction+)?)?
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//('with' witnesses+=XWitness+)? 'begin' actions+=XAction+
		public Group getGroup_5_0() { return cGroup_5_0; }
		
		//('with' witnesses+=XWitness+)?
		public Group getGroup_5_0_0() { return cGroup_5_0_0; }
		
		//'with'
		public Keyword getWithKeyword_5_0_0_0() { return cWithKeyword_5_0_0_0; }
		
		//witnesses+=XWitness+
		public Assignment getWitnessesAssignment_5_0_0_1() { return cWitnessesAssignment_5_0_0_1; }
		
		//XWitness
		public RuleCall getWitnessesXWitnessParserRuleCall_5_0_0_1_0() { return cWitnessesXWitnessParserRuleCall_5_0_0_1_0; }
		
		//'begin'
		public Keyword getBeginKeyword_5_0_1() { return cBeginKeyword_5_0_1; }
		
		//actions+=XAction+
		public Assignment getActionsAssignment_5_0_2() { return cActionsAssignment_5_0_2; }
		
		//XAction
		public RuleCall getActionsXActionParserRuleCall_5_0_2_0() { return cActionsXActionParserRuleCall_5_0_2_0; }
		
		//'when' guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then' actions+=XAction+)?
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//'when'
		public Keyword getWhenKeyword_5_1_0() { return cWhenKeyword_5_1_0; }
		
		//guards+=XGuard+
		public Assignment getGuardsAssignment_5_1_1() { return cGuardsAssignment_5_1_1; }
		
		//XGuard
		public RuleCall getGuardsXGuardParserRuleCall_5_1_1_0() { return cGuardsXGuardParserRuleCall_5_1_1_0; }
		
		//('with' witnesses+=XWitness+)?
		public Group getGroup_5_1_2() { return cGroup_5_1_2; }
		
		//'with'
		public Keyword getWithKeyword_5_1_2_0() { return cWithKeyword_5_1_2_0; }
		
		//witnesses+=XWitness+
		public Assignment getWitnessesAssignment_5_1_2_1() { return cWitnessesAssignment_5_1_2_1; }
		
		//XWitness
		public RuleCall getWitnessesXWitnessParserRuleCall_5_1_2_1_0() { return cWitnessesXWitnessParserRuleCall_5_1_2_1_0; }
		
		//('then' actions+=XAction+)?
		public Group getGroup_5_1_3() { return cGroup_5_1_3; }
		
		//'then'
		public Keyword getThenKeyword_5_1_3_0() { return cThenKeyword_5_1_3_0; }
		
		//actions+=XAction+
		public Assignment getActionsAssignment_5_1_3_1() { return cActionsAssignment_5_1_3_1; }
		
		//XAction
		public RuleCall getActionsXActionParserRuleCall_5_1_3_1_0() { return cActionsXActionParserRuleCall_5_1_3_1_0; }
		
		//'any' parameters+=XParameter+ 'where' guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then' actions+=XAction+)?
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//'any'
		public Keyword getAnyKeyword_5_2_0() { return cAnyKeyword_5_2_0; }
		
		//parameters+=XParameter+
		public Assignment getParametersAssignment_5_2_1() { return cParametersAssignment_5_2_1; }
		
		//XParameter
		public RuleCall getParametersXParameterParserRuleCall_5_2_1_0() { return cParametersXParameterParserRuleCall_5_2_1_0; }
		
		//'where'
		public Keyword getWhereKeyword_5_2_2() { return cWhereKeyword_5_2_2; }
		
		//guards+=XGuard+
		public Assignment getGuardsAssignment_5_2_3() { return cGuardsAssignment_5_2_3; }
		
		//XGuard
		public RuleCall getGuardsXGuardParserRuleCall_5_2_3_0() { return cGuardsXGuardParserRuleCall_5_2_3_0; }
		
		//('with' witnesses+=XWitness+)?
		public Group getGroup_5_2_4() { return cGroup_5_2_4; }
		
		//'with'
		public Keyword getWithKeyword_5_2_4_0() { return cWithKeyword_5_2_4_0; }
		
		//witnesses+=XWitness+
		public Assignment getWitnessesAssignment_5_2_4_1() { return cWitnessesAssignment_5_2_4_1; }
		
		//XWitness
		public RuleCall getWitnessesXWitnessParserRuleCall_5_2_4_1_0() { return cWitnessesXWitnessParserRuleCall_5_2_4_1_0; }
		
		//('then' actions+=XAction+)?
		public Group getGroup_5_2_5() { return cGroup_5_2_5; }
		
		//'then'
		public Keyword getThenKeyword_5_2_5_0() { return cThenKeyword_5_2_5_0; }
		
		//actions+=XAction+
		public Assignment getActionsAssignment_5_2_5_1() { return cActionsAssignment_5_2_5_1; }
		
		//XAction
		public RuleCall getActionsXActionParserRuleCall_5_2_5_1_0() { return cActionsXActionParserRuleCall_5_2_5_1_0; }
		
		//'end'
		public Keyword getEndKeyword_6() { return cEndKeyword_6; }
	}
	public class EventSyncElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.EventSync");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventSynchronisationAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSynchronisesKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cPrefixAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cPrefixIDTerminalRuleCall_1_1_0_0 = (RuleCall)cPrefixAssignment_1_1_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cSynchronisedEventAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cSynchronisedEventEventCrossReference_1_2_0 = (CrossReference)cSynchronisedEventAssignment_1_2.eContents().get(0);
		private final RuleCall cSynchronisedEventEventIDTerminalRuleCall_1_2_0_1 = (RuleCall)cSynchronisedEventEventCrossReference_1_2_0.eContents().get(1);
		
		//EventSync einclusion::EventSynchronisation:
		//	{einclusion::EventSynchronisation} ('synchronises' (prefix=ID '.')? synchronisedEvent=[emachine::Event]);
		@Override public ParserRule getRule() { return rule; }
		
		//{einclusion::EventSynchronisation} ('synchronises' (prefix=ID '.')? synchronisedEvent=[emachine::Event])
		public Group getGroup() { return cGroup; }
		
		//{einclusion::EventSynchronisation}
		public Action getEventSynchronisationAction_0() { return cEventSynchronisationAction_0; }
		
		//'synchronises' (prefix=ID '.')? synchronisedEvent=[emachine::Event]
		public Group getGroup_1() { return cGroup_1; }
		
		//'synchronises'
		public Keyword getSynchronisesKeyword_1_0() { return cSynchronisesKeyword_1_0; }
		
		//(prefix=ID '.')?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//prefix=ID
		public Assignment getPrefixAssignment_1_1_0() { return cPrefixAssignment_1_1_0; }
		
		//ID
		public RuleCall getPrefixIDTerminalRuleCall_1_1_0_0() { return cPrefixIDTerminalRuleCall_1_1_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1_1() { return cFullStopKeyword_1_1_1; }
		
		//synchronisedEvent=[emachine::Event]
		public Assignment getSynchronisedEventAssignment_1_2() { return cSynchronisedEventAssignment_1_2; }
		
		//[emachine::Event]
		public CrossReference getSynchronisedEventEventCrossReference_1_2_0() { return cSynchronisedEventEventCrossReference_1_2_0; }
		
		//ID
		public RuleCall getSynchronisedEventEventIDTerminalRuleCall_1_2_0_1() { return cSynchronisedEventEventIDTerminalRuleCall_1_2_0_1; }
	}
	public class XParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XParameter emachine::Parameter:
		//	{emachine::Parameter} name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Parameter} name=ID
		public Group getGroup() { return cGroup; }
		
		//{emachine::Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class XGuardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XGuard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGuardAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameXLABELTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPredicateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPredicateXPredicateParserRuleCall_2_0 = (RuleCall)cPredicateAssignment_2.eContents().get(0);
		private final Assignment cTheoremAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cTheoremTheoremKeyword_3_0 = (Keyword)cTheoremAssignment_3.eContents().get(0);
		
		//XGuard emachine::Guard:
		//	{emachine::Guard} name=XLABEL predicate=XPredicate theorem?='theorem'?;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Guard} name=XLABEL predicate=XPredicate theorem?='theorem'?
		public Group getGroup() { return cGroup; }
		
		//{emachine::Guard}
		public Action getGuardAction_0() { return cGuardAction_0; }
		
		//name=XLABEL
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//XLABEL
		public RuleCall getNameXLABELTerminalRuleCall_1_0() { return cNameXLABELTerminalRuleCall_1_0; }
		
		//predicate=XPredicate
		public Assignment getPredicateAssignment_2() { return cPredicateAssignment_2; }
		
		//XPredicate
		public RuleCall getPredicateXPredicateParserRuleCall_2_0() { return cPredicateXPredicateParserRuleCall_2_0; }
		
		//theorem?='theorem'?
		public Assignment getTheoremAssignment_3() { return cTheoremAssignment_3; }
		
		//'theorem'
		public Keyword getTheoremTheoremKeyword_3_0() { return cTheoremTheoremKeyword_3_0; }
	}
	public class XWitnessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XWitness");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWitnessAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameXLABELTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPredicateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPredicateXPredicateParserRuleCall_2_0 = (RuleCall)cPredicateAssignment_2.eContents().get(0);
		
		//XWitness emachine::Witness:
		//	{emachine::Witness} name=XLABEL predicate=XPredicate;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Witness} name=XLABEL predicate=XPredicate
		public Group getGroup() { return cGroup; }
		
		//{emachine::Witness}
		public Action getWitnessAction_0() { return cWitnessAction_0; }
		
		//name=XLABEL
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//XLABEL
		public RuleCall getNameXLABELTerminalRuleCall_1_0() { return cNameXLABELTerminalRuleCall_1_0; }
		
		//predicate=XPredicate
		public Assignment getPredicateAssignment_2() { return cPredicateAssignment_2; }
		
		//XPredicate
		public RuleCall getPredicateXPredicateParserRuleCall_2_0() { return cPredicateXPredicateParserRuleCall_2_0; }
	}
	public class XActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameXLABELTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cActionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cActionXPredicateParserRuleCall_2_0 = (RuleCall)cActionAssignment_2.eContents().get(0);
		
		//XAction emachine::Action:
		//	{emachine::Action} name=XLABEL action=XPredicate;
		@Override public ParserRule getRule() { return rule; }
		
		//{emachine::Action} name=XLABEL action=XPredicate
		public Group getGroup() { return cGroup; }
		
		//{emachine::Action}
		public Action getActionAction_0() { return cActionAction_0; }
		
		//name=XLABEL
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//XLABEL
		public RuleCall getNameXLABELTerminalRuleCall_1_0() { return cNameXLABELTerminalRuleCall_1_0; }
		
		//action=XPredicate
		public Assignment getActionAssignment_2() { return cActionAssignment_2; }
		
		//XPredicate
		public RuleCall getActionXPredicateParserRuleCall_2_0() { return cActionXPredicateParserRuleCall_2_0; }
	}
	public class XPredicateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XPredicate");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//XPredicate:
		//	STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	public class XConvergenceElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XConvergence");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOrdinaryEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOrdinaryOrdinaryKeyword_0_0 = (Keyword)cOrdinaryEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cConvergentEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cConvergentConvergentKeyword_1_0 = (Keyword)cConvergentEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAnticipatedEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAnticipatedAnticipatedKeyword_2_0 = (Keyword)cAnticipatedEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum XConvergence returns emachine::Convergence:
		//	ordinary | convergent | anticipated;
		public EnumRule getRule() { return rule; }
		
		//ordinary | convergent | anticipated
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ordinary
		public EnumLiteralDeclaration getOrdinaryEnumLiteralDeclaration_0() { return cOrdinaryEnumLiteralDeclaration_0; }
		
		//'ordinary'
		public Keyword getOrdinaryOrdinaryKeyword_0_0() { return cOrdinaryOrdinaryKeyword_0_0; }
		
		//convergent
		public EnumLiteralDeclaration getConvergentEnumLiteralDeclaration_1() { return cConvergentEnumLiteralDeclaration_1; }
		
		//'convergent'
		public Keyword getConvergentConvergentKeyword_1_0() { return cConvergentConvergentKeyword_1_0; }
		
		//anticipated
		public EnumLiteralDeclaration getAnticipatedEnumLiteralDeclaration_2() { return cAnticipatedEnumLiteralDeclaration_2; }
		
		//'anticipated'
		public Keyword getAnticipatedAnticipatedKeyword_2_0() { return cAnticipatedAnticipatedKeyword_2_0; }
	}
	
	private final MachineElements pMachine;
	private final MIncludesElements pMIncludes;
	private final QualifiedNameElements pQualifiedName;
	private final XVariableElements pXVariable;
	private final XInvariantElements pXInvariant;
	private final TerminalRule tXLABEL;
	private final XVariantElements pXVariant;
	private final XEventElements pXEvent;
	private final EventSyncElements pEventSync;
	private final XConvergenceElements eXConvergence;
	private final XParameterElements pXParameter;
	private final XGuardElements pXGuard;
	private final XWitnessElements pXWitness;
	private final XActionElements pXAction;
	private final XPredicateElements pXPredicate;
	private final TerminalRule tID;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XMachineGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMachine = new MachineElements();
		this.pMIncludes = new MIncludesElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pXVariable = new XVariableElements();
		this.pXInvariant = new XInvariantElements();
		this.tXLABEL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.XLABEL");
		this.pXVariant = new XVariantElements();
		this.pXEvent = new XEventElements();
		this.pEventSync = new EventSyncElements();
		this.eXConvergence = new XConvergenceElements();
		this.pXParameter = new XParameterElements();
		this.pXGuard = new XGuardElements();
		this.pXWitness = new XWitnessElements();
		this.pXAction = new XActionElements();
		this.pXPredicate = new XPredicateElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xeventb.xmachine.XMachine.ID");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ac.soton.xeventb.xmachine.XMachine".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * For XEvent-B 0.0.8 comments are allowed everywhere
	// * ML_COMMENT and SL_COMMEN are defined as hidden
	// */ Machine emachine::Machine:
	//	{emachine::Machine} comment=(ML_COMMENT | SL_COMMENT)?
	//	'machine' name=ID
	//	extensions+=MIncludes* ('refines' refines+=[emachine::Machine])? ('sees' sees+=[econtext::Context]+)? ('variables'
	//	variables+=XVariable+)? ('invariants' invariants+=XInvariant+)? ('variant' variant=XVariant)? ('events' events+=XEvent
	//	events+=XEvent*)?
	//	'end';
	public MachineElements getMachineAccess() {
		return pMachine;
	}
	
	public ParserRule getMachineRule() {
		return getMachineAccess().getRule();
	}
	
	//MIncludes einclusion::MachineInclusion:
	//	{einclusion::MachineInclusion} ('includes' abstractMachine=[emachine::Machine|QualifiedName]) ('to'
	//	concreteMachine=[emachine::Machine])? ('as' prefixes+=ID prefixes+=ID*)?;
	public MIncludesElements getMIncludesAccess() {
		return pMIncludes;
	}
	
	public ParserRule getMIncludesRule() {
		return getMIncludesAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)?;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//XVariable emachine::Variable:
	//	{emachine::Variable} name=ID;
	public XVariableElements getXVariableAccess() {
		return pXVariable;
	}
	
	public ParserRule getXVariableRule() {
		return getXVariableAccess().getRule();
	}
	
	//XInvariant emachine::Invariant:
	//	{emachine::Invariant} name=XLABEL predicate=XPredicate theorem?='theorem'?;
	public XInvariantElements getXInvariantAccess() {
		return pXInvariant;
	}
	
	public ParserRule getXInvariantRule() {
		return getXInvariantAccess().getRule();
	}
	
	//terminal XLABEL:
	//	'@' !':'+ ':';
	public TerminalRule getXLABELRule() {
		return tXLABEL;
	}
	
	//XVariant emachine::Variant:
	//	{emachine::Variant} expression=XPredicate;
	public XVariantElements getXVariantAccess() {
		return pXVariant;
	}
	
	public ParserRule getXVariantRule() {
		return getXVariantAccess().getRule();
	}
	
	//XEvent emachine::Event:
	//	{emachine::Event} name=ID (extended?='extended'? & convergence=XConvergence?) extensions+=EventSync* ('refines'
	//	refines+=[emachine::Event]+)? (('with' witnesses+=XWitness+)?
	//	'begin'
	//	actions+=XAction+
	//	|
	//	'when'
	//	guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then'
	//	actions+=XAction+)?
	//	|
	//	'any'
	//	parameters+=XParameter+
	//	'where'
	//	guards+=XGuard+ ('with' witnesses+=XWitness+)? ('then'
	//	actions+=XAction+)?)?
	//	'end';
	public XEventElements getXEventAccess() {
		return pXEvent;
	}
	
	public ParserRule getXEventRule() {
		return getXEventAccess().getRule();
	}
	
	//EventSync einclusion::EventSynchronisation:
	//	{einclusion::EventSynchronisation} ('synchronises' (prefix=ID '.')? synchronisedEvent=[emachine::Event]);
	public EventSyncElements getEventSyncAccess() {
		return pEventSync;
	}
	
	public ParserRule getEventSyncRule() {
		return getEventSyncAccess().getRule();
	}
	
	//enum XConvergence returns emachine::Convergence:
	//	ordinary | convergent | anticipated;
	public XConvergenceElements getXConvergenceAccess() {
		return eXConvergence;
	}
	
	public EnumRule getXConvergenceRule() {
		return getXConvergenceAccess().getRule();
	}
	
	//XParameter emachine::Parameter:
	//	{emachine::Parameter} name=ID;
	public XParameterElements getXParameterAccess() {
		return pXParameter;
	}
	
	public ParserRule getXParameterRule() {
		return getXParameterAccess().getRule();
	}
	
	//XGuard emachine::Guard:
	//	{emachine::Guard} name=XLABEL predicate=XPredicate theorem?='theorem'?;
	public XGuardElements getXGuardAccess() {
		return pXGuard;
	}
	
	public ParserRule getXGuardRule() {
		return getXGuardAccess().getRule();
	}
	
	//XWitness emachine::Witness:
	//	{emachine::Witness} name=XLABEL predicate=XPredicate;
	public XWitnessElements getXWitnessAccess() {
		return pXWitness;
	}
	
	public ParserRule getXWitnessRule() {
		return getXWitnessAccess().getRule();
	}
	
	//XAction emachine::Action:
	//	{emachine::Action} name=XLABEL action=XPredicate;
	public XActionElements getXActionAccess() {
		return pXAction;
	}
	
	public ParserRule getXActionRule() {
		return getXActionAccess().getRule();
	}
	
	//XPredicate:
	//	STRING;
	public XPredicateElements getXPredicateAccess() {
		return pXPredicate;
	}
	
	public ParserRule getXPredicateRule() {
		return getXPredicateAccess().getRule();
	}
	
	//@ Override terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_' | 'i'..'ￜ') ('a'..'z' | 'A'..'Z' | '_' | 'i'..'ￜ' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
