/**
 * generated by Xtext 2.11.0
 */
package ac.soton.eventb.xtext.context.ide;

import ac.soton.eventb.xtext.context.ide.AbstractXContextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XContextIdeModule extends AbstractXContextIdeModule {
}
