/*
 * generated by Xtext
 */
package ac.soton.xeventb.xmachine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ac.soton.xeventb.xmachine.ui.internal.XMachineActivator.getInstance().getInjector("ac.soton.xeventb.xmachine.XMachine");
	}

}
