/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xeventb.camillex


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EventBComponentStandaloneSetup extends EventBComponentStandaloneSetupGenerated {

	def static void doSetup() {
		new EventBComponentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
