/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xeventb.camillex;

import ac.soton.xeventb.camillex.EventBComponentStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EventBComponentStandaloneSetup extends EventBComponentStandaloneSetupGenerated {
  public static void doSetup() {
    new EventBComponentStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
