/*
 * generated by Xtext 2.25.0
 */
package ac.soton.xeventb.xmachine.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXMachineScopeProvider extends DelegatingScopeProvider {
}
