/*
 * generated by Xtext 2.10.0
 */
package ac.soton.eventb.xtext.machine.ui;

import ac.soton.eventb.xtext.machine.ui.internal.MachineActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MachineActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MachineActivator.getInstance().getInjector(MachineActivator.AC_SOTON_EVENTB_XTEXT_MACHINE_XMACHINE);
	}
	
}
