/*
 * generated by Xtext 2.11.0
 */
package ac.soton.xeventb.xstatemachine.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class XStatemachineScopeProvider extends AbstractXStatemachineScopeProvider {

}
